name: api-dbreast

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v2        

            - name: List files in root directory
              run: ls

            - name: List files in root directory
              run: |
                cd ./.. 
                ls

            - name: List files in root directory
              run: |
                cd ./../..
                ls

            - name: build Docker image
              run: docker build -t lansingbusinesssystems/api-dbreast:qa-1.26 .

            - name: push Docker image
              run: docker push lansingbusinesssystems/api-dbreast:qa-1.26

